fix : config pre-push setting

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -17,12 +17,19 @@ yarn check-types ||
     false;
 )
 
-yarn check-eslint:dev ||
+yarn check-eslint ||
 (
         echo '😤🏀👋😤 Get that weak shit out of here! 😤🏀👋😤 
                 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
         false; 
 )
+
+# yarn check-eslint:dev ||
+# (
+#         echo '😤🏀👋😤 Get that weak shit out of here! 😤🏀👋😤 
+#                 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
+#         false; 
+# )
 
 # yarn test:ci ||
 # (
@@ -33,7 +40,7 @@ yarn check-eslint:dev ||
 # # If everything passes... Now we can commit
 # # echo '🤔🤔🤔🤔... Alright.... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'
 
-yarn build ||
+yarn build:dev ||
 (
     echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
             Next build failed: View the errors above to see why. 
